import { addDays, format } from 'date-fns';
import type {
  Account,
  Bill,
  CategoryRule,
  CreditCard,
  FinanceDataState,
  Loan,
  MonthlyBudget,
  RecurringTransactionRule,
  SavingsGoal,
  Transaction,
} from '@/types/finance';
import { CATEGORY_COLOR_PALETTE } from '@/lib/transactionCategories';
import { deriveLoanMonthlyInterestRate } from '@/lib/interest';

const uid = (prefix: string) => `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
const today = new Date();
const isoDaysAgo = (days: number) => format(addDays(today, -days), 'yyyy-MM-dd');
const isoDaysFromNow = (days: number) => format(addDays(today, days), 'yyyy-MM-dd');

const assignColors = (categories: string[]) =>
  categories.reduce<Record<string, string>>((map, category, index) => {
    map[category] = CATEGORY_COLOR_PALETTE[index % CATEGORY_COLOR_PALETTE.length];
    return map;
  }, {});

export const generateSampleFinanceData = (currency = '₱'): FinanceDataState => {
  const accounts: Account[] = [
    { id: uid('acc'), name: 'Main Bank', type: 'bank', balance: 52480, currency, color: '#0ea5e9' },
    { id: uid('acc'), name: 'Daily Wallet', type: 'e-wallet', balance: 4280, currency, color: '#22c55e' },
  ];

  const transactions: Transaction[] = [
    {
      id: uid('tx'),
      accountId: accounts[0].id,
      type: 'income',
      amount: 45000,
      category: 'Salary',
      categories: ['Salary'],
      description: 'Monthly salary',
      date: isoDaysAgo(4),
      tags: ['payday'],
    },
    {
      id: uid('tx'),
      accountId: accounts[1].id,
      type: 'expense',
      amount: 1680,
      category: 'Food',
      categories: ['Food', 'Groceries'],
      description: 'Weekly groceries',
      date: isoDaysAgo(2),
      tags: ['family'],
    },
    {
      id: uid('tx'),
      accountId: accounts[1].id,
      type: 'expense',
      amount: 540,
      category: 'Transport',
      categories: ['Transport'],
      description: 'Ride share and commute',
      date: isoDaysAgo(1),
      tags: ['work'],
    },
    {
      id: uid('tx'),
      accountId: accounts[0].id,
      type: 'expense',
      amount: 12000,
      category: 'Rent',
      categories: ['Rent'],
      description: 'Monthly rent',
      date: isoDaysAgo(6),
      tags: ['fixed'],
    },
    {
      id: uid('tx'),
      accountId: accounts[0].id,
      type: 'expense',
      amount: 2200,
      category: 'Utilities',
      categories: ['Utilities'],
      description: 'Electricity and internet',
      date: isoDaysAgo(8),
      tags: ['bills'],
    },
    {
      id: uid('tx'),
      accountId: accounts[1].id,
      type: 'expense',
      amount: 2400,
      category: 'Shopping',
      categories: ['Shopping'],
      description: 'Clothes and essentials',
      date: isoDaysAgo(10),
      tags: ['personal'],
    },
    {
      id: uid('tx'),
      accountId: accounts[0].id,
      type: 'income',
      amount: 8000,
      category: 'Freelance',
      categories: ['Freelance'],
      description: 'Side project payment',
      date: isoDaysAgo(12),
      tags: ['extra'],
    },
  ];

  const recurringTransactionRules: RecurringTransactionRule[] = [
    {
      id: uid('rr'),
      label: 'Monthly Salary',
      accountId: accounts[0].id,
      type: 'income',
      amount: 45000,
      category: 'Salary',
      description: 'Recurring salary deposit',
      frequency: 'monthly',
      startDate: isoDaysAgo(30),
      nextRunDate: isoDaysFromNow(2),
      active: true,
      createdAt: isoDaysAgo(30),
      lastGeneratedDate: isoDaysAgo(4),
    },
    {
      id: uid('rr'),
      label: 'Weekly Allowance Top-up',
      accountId: accounts[1].id,
      type: 'income',
      amount: 1200,
      category: 'Allowance',
      description: 'Weekly wallet top-up',
      frequency: 'weekly',
      startDate: isoDaysAgo(21),
      nextRunDate: isoDaysFromNow(1),
      active: true,
      createdAt: isoDaysAgo(21),
      lastGeneratedDate: isoDaysAgo(6),
    },
    {
      id: uid('rr'),
      label: 'Biweekly Rent Reserve',
      accountId: accounts[0].id,
      type: 'expense',
      amount: 6000,
      category: 'Rent',
      description: 'Reserve for upcoming rent payment',
      frequency: 'biweekly',
      startDate: isoDaysAgo(28),
      nextRunDate: isoDaysFromNow(4),
      active: true,
      createdAt: isoDaysAgo(28),
      lastGeneratedDate: isoDaysAgo(10),
    },
    {
      id: uid('rr'),
      label: 'Gym Membership',
      accountId: accounts[1].id,
      type: 'expense',
      amount: 650,
      category: 'Health',
      description: 'Recurring gym charge (paused)',
      frequency: 'monthly',
      startDate: isoDaysAgo(60),
      nextRunDate: isoDaysFromNow(8),
      active: false,
      createdAt: isoDaysAgo(60),
      lastGeneratedDate: isoDaysAgo(32),
    },
    {
      id: uid('rr'),
      label: 'Reading App Subscription',
      accountId: accounts[1].id,
      type: 'expense',
      amount: 199,
      category: 'Subscriptions',
      description: 'Custom every 10 days plan',
      frequency: 'custom',
      intervalDays: 10,
      startDate: isoDaysAgo(30),
      nextRunDate: isoDaysFromNow(2),
      active: true,
      createdAt: isoDaysAgo(30),
      lastGeneratedDate: isoDaysAgo(8),
    },
  ];

  const categoryRules: CategoryRule[] = [
    {
      id: uid('cr'),
      pattern: 'salary',
      category: 'Salary',
      matchType: 'contains',
      active: true,
      createdAt: isoDaysAgo(30),
      updatedAt: isoDaysAgo(2),
    },
    {
      id: uid('cr'),
      pattern: 'grab',
      category: 'Transport',
      matchType: 'contains',
      active: true,
      createdAt: isoDaysAgo(24),
      updatedAt: isoDaysAgo(1),
    },
    {
      id: uid('cr'),
      pattern: 'rent',
      category: 'Rent',
      matchType: 'contains',
      active: true,
      createdAt: isoDaysAgo(18),
      updatedAt: isoDaysAgo(4),
    },
  ];

  const transactionCategories = ['Allowance', 'Groceries', 'Subscriptions'];
  const savingsCategories = ['Travel', 'Retirement'];
  const sharedCategories = ['Utilities', 'Education', 'Rent'];

  const budgets: MonthlyBudget[] = [
    {
      id: uid('bd'),
      category: 'Food',
      limitAmount: 9000,
      alertThresholdPct: 80,
      active: true,
      createdAt: isoDaysAgo(30),
      updatedAt: isoDaysAgo(3),
    },
    {
      id: uid('bd'),
      category: 'Transport',
      limitAmount: 4000,
      alertThresholdPct: 80,
      active: true,
      createdAt: isoDaysAgo(30),
      updatedAt: isoDaysAgo(3),
    },
  ];

  const motorLoanSchedule = [
    { id: uid('sched'), dueDate: isoDaysAgo(6), amount: 48000, paidAmount: 12000 },
    { id: uid('sched'), dueDate: isoDaysFromNow(3), amount: 52000, paidAmount: 0 },
    { id: uid('sched'), dueDate: isoDaysFromNow(33), amount: 56000, paidAmount: 0 },
    { id: uid('sched'), dueDate: isoDaysFromNow(63), amount: 54000, paidAmount: 0 },
  ];
  const motorLoanMonthlyPayment = motorLoanSchedule.reduce((sum, entry) => sum + entry.amount, 0) / motorLoanSchedule.length;

  const loans: Loan[] = [
    {
      id: uid('loan'),
      name: 'Motor Loan',
      totalAmount: 180000,
      paidAmount: 12000,
      monthlyPayment: motorLoanMonthlyPayment,
      monthlyInterestRate: deriveLoanMonthlyInterestRate({
        totalAmount: 180000,
        monthlyPayment: motorLoanMonthlyPayment,
        startDate: motorLoanSchedule[0].dueDate,
        endDate: motorLoanSchedule[motorLoanSchedule.length - 1].dueDate,
        dueDay: 15,
        repaymentSchedule: motorLoanSchedule,
      }),
      startDate: motorLoanSchedule[0].dueDate,
      dueDay: 15,
      endDate: motorLoanSchedule[motorLoanSchedule.length - 1].dueDate,
      repaymentSchedule: motorLoanSchedule,
      type: 'loan',
    },
    {
      id: uid('loan'),
      name: 'Laptop Installment',
      totalAmount: 72000,
      paidAmount: 18000,
      monthlyPayment: 9000,
      monthlyInterestRate: 0,
      startDate: isoDaysAgo(90),
      dueDay: 10,
      endDate: isoDaysFromNow(150),
      repaymentSchedule: [
        { id: uid('sched'), dueDate: isoDaysAgo(2), amount: 9000, paidAmount: 4000 },
        { id: uid('sched'), dueDate: isoDaysFromNow(5), amount: 9000, paidAmount: 0 },
        { id: uid('sched'), dueDate: isoDaysFromNow(35), amount: 9000, paidAmount: 0 },
      ],
      type: 'installment',
    },
  ];

  const creditCards: CreditCard[] = [
    {
      id: uid('cc'),
      name: 'Rewards Visa',
      issuer: 'Finbo Bank',
      network: 'visa',
      creditLimit: 50000,
      paidAmount: 41600,
      currentBalance: 8400,
      statementBalance: 9200,
      minimumPayment: 2500,
      monthlyInterestRate: 3.25,
      rewardsRate: 1.2,
      annualFee: 1500,
      dueDate: isoDaysFromNow(2),
      statementCloseDate: isoDaysAgo(3),
      openedDate: isoDaysAgo(420),
      autopay: false,
      rewardsPoints: 1840,
      lastPaymentDate: isoDaysAgo(18),
    },
    {
      id: uid('cc'),
      name: 'Essentials Mastercard',
      issuer: 'Metro Union',
      network: 'mastercard',
      creditLimit: 35000,
      paidAmount: 14000,
      currentBalance: 4600,
      statementBalance: 4800,
      minimumPayment: 1200,
      monthlyInterestRate: 2.9,
      rewardsRate: 0.8,
      annualFee: 1200,
      dueDate: isoDaysAgo(4),
      statementCloseDate: isoDaysAgo(12),
      openedDate: isoDaysAgo(620),
      autopay: false,
      rewardsPoints: 960,
      lastPaymentDate: isoDaysAgo(40),
    },
  ];

  const bills: Bill[] = [
    {
      id: uid('bill'),
      name: 'Internet Fiber',
      amount: 1899,
      category: 'Utilities',
      dueDate: isoDaysFromNow(2),
      recurring: true,
      frequency: 'monthly',
      active: true,
      status: 'pending',
    },
    {
      id: uid('bill'),
      name: 'Water Bill',
      amount: 760,
      category: 'Utilities',
      dueDate: isoDaysAgo(5),
      recurring: true,
      frequency: 'monthly',
      active: true,
      status: 'overdue',
    },
    {
      id: uid('bill'),
      name: 'Streaming',
      amount: 499,
      category: 'Entertainment',
      dueDate: isoDaysFromNow(6),
      recurring: true,
      frequency: 'weekly',
      active: true,
      status: 'pending',
    },
    {
      id: uid('bill'),
      name: 'Cloud Storage',
      amount: 149,
      category: 'Subscriptions',
      dueDate: isoDaysFromNow(4),
      recurring: true,
      frequency: 'custom',
      intervalDays: 10,
      active: false,
      status: 'pending',
    },
    {
      id: uid('bill'),
      name: 'School Supplies',
      amount: 1250,
      category: 'Education',
      dueDate: isoDaysAgo(9),
      recurring: false,
      active: true,
      status: 'pending',
    },
  ];

  const savingsGoals: SavingsGoal[] = [
    {
      id: uid('goal'),
      name: 'Emergency Fund',
      category: 'Emergency Fund',
      targetAmount: 100000,
      savedAmount: 28000,
      targetDate: isoDaysFromNow(180),
      createdAt: isoDaysAgo(70),
      note: 'Build a 6-month safety net.',
    },
  ];

  const categoryColors = assignColors([
    'Salary',
    'Food',
    'Groceries',
    'Transport',
    'Rent',
    'Utilities',
    'Shopping',
    'Freelance',
    'Entertainment',
    'Allowance',
    'Health',
    'Subscriptions',
    'Education',
    'Emergency Fund',
  ]);

  return {
    accounts,
    transactions,
    recurringTransactionRules,
    categoryRules,
    transactionCategories,
    savingsCategories,
    sharedCategories,
    budgets,
    categoryColors,
    loans,
    loanPayments: [],
    creditCards,
    creditCardActivities: [],
    bills,
    savingsGoals,
    savingsGoalContributions: [],
    currency,
  };
};
